[package]

authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "termios"
version = "0.0.0"

[build-dependencies.rust-bindgen]
branch = "static"
features = ["static"]
git = "https://github.com/japaric/rust-bindgen"
